// Generated by Skyramp v1.3.40 on 2026-08-29 15:22:42.395216664 +0000 UTC m=+436.806409192
// Command: skyramp generate contract rest http://localhost:5050/record \
// 		--framework playwright \
// 		--language javascript \
// 		--method POST \
// 		--output-dir /home/runner/work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests/skyramp/mern-records-backend \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_record_create_returns_201.spec.js \
// 		--request-data {"name":"Status Probe","position":"Engineer","level":"Junior","department":"Platform"} \
// 		--response-status-code 201 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, SkyrampClient, getBaseUrl, getResponseValue } from '@skyramp/skyramp';
import assert from 'node:assert';
import { create_record } from './skyrampUtils.js';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5050");

// contract test for /record POST
test('testRecordPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const recordPostRequestBody = `{
        "department": "Platform",
        "level": "Junior",
        "name": "Status Probe",
        "position": "Engineer"
    }`;

    const recordPostResponse = await create_record(client, URL, recordPostRequestBody, 201, headers);
    assert.strictEqual(getResponseValue(recordPostResponse, "acknowledged"), true, 'acknowledged');
    assert.match(String(getResponseValue(recordPostResponse, "insertedId")), /^[0-9a-f]{24}$/i, 'insertedId');
});
