// Generated by Skyramp v1.3.40 on 2026-08-29 15:22:35.960353568 +0000 UTC m=+430.371546095
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language javascript \
// 		--output record_patch_partial_update_preserves_department_integration_test.spec.js \
// 		--output-dir /home/runner/work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests/skyramp/mern-records-backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests/skyramp/mern-records-backend/scenario_record-patch-partial-update-preserves-department.json

// Import of required libraries
import { test, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import assert from 'node:assert';
import { create_record, update_record, get_record } from './skyrampUtils.js';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5050");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const recordPostRequestBody = `{
        "department": "Infrastructure",
        "level": "Junior",
        "name": "Priya Raman",
        "position": "Platform Engineer"
    }`;

    const recordPostResponse = await create_record(client, URL_localhost, recordPostRequestBody, 200);
    assert.strictEqual(getResponseValue(recordPostResponse, "acknowledged"), true, 'acknowledged');
    assert.match(String(getResponseValue(recordPostResponse, "insertedId")), /^[0-9a-f]{24}$/i, 'insertedId');

    // Request Body
    const recordRecordPatchRequestBody = `{
        "level": "Senior"
    }`;

    const recordRecordPatchResponse = await update_record(client, URL_localhost, getResponseValue(recordPostResponse, "insertedId"), recordRecordPatchRequestBody, 200);
    assert.strictEqual(getResponseValue(recordRecordPatchResponse, "acknowledged"), true, 'acknowledged');
    assert.strictEqual(getResponseValue(recordRecordPatchResponse, "matchedCount"), 1, 'matchedCount');
    assert.strictEqual(getResponseValue(recordRecordPatchResponse, "modifiedCount"), 1, 'modifiedCount');

    const recordRecordGetResponse = await get_record(client, URL_localhost, getResponseValue(recordPostResponse, "insertedId"), 200);
    assert.strictEqual(getResponseValue(recordRecordGetResponse, "_id"), getResponseValue(recordPostResponse, "insertedId"), '_id');
    assert.strictEqual(getResponseValue(recordRecordGetResponse, "level"), "Senior", 'level');
    assert.strictEqual(getResponseValue(recordRecordGetResponse, "name"), "Priya Raman", 'name');
    assert.strictEqual(getResponseValue(recordRecordGetResponse, "position"), "Platform Engineer", 'position');
    assert.strictEqual(getResponseValue(recordRecordGetResponse, "department"), "Infrastructure", 'department');
});
