// Generated by Skyramp on 2026-08-29 15:25:26.461 Coordinated Universal Time


import assert from 'node:assert';

export async function create_record(client, url, body, expectedStatus = 200, headers = {}) {
    // Execute Request
    const recordPostResponse = await client.sendRequest({
        url: url,
        path: "/record",
        method: "POST",
        body: body,
        headers: headers
    });

    // Generated Assertions
    assert.strictEqual(recordPostResponse.statusCode, expectedStatus, 'status code');

    return recordPostResponse;
}

export async function update_record(client, url, recordId, body, expectedStatus = 200) {
    // Execute Request
    const recordRecordPatchResponse = await client.sendRequest({
        url: url,
        path: "/record/{record}",
        method: "PATCH",
        body: body,
        pathParams: {"record": recordId}
    });

    // Generated Assertions
    assert.strictEqual(recordRecordPatchResponse.statusCode, expectedStatus, 'status code');

    return recordRecordPatchResponse;
}

export async function get_record(client, url, recordId, expectedStatus = 200) {
    // Execute Request
    const recordRecordGetResponse = await client.sendRequest({
        url: url,
        path: "/record/{record}",
        method: "GET",
        pathParams: {"record": recordId}
    });

    // Generated Assertions
    assert.strictEqual(recordRecordGetResponse.statusCode, expectedStatus, 'status code');

    return recordRecordGetResponse;
}
