// Generated by Skyramp v1.3.38 on 2026-08-19 17:28:23.376718 -0700 PDT m=+910.935555751
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output department_column_create_new_employee.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/.skyramp/department_column_create_employee_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5173");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(191000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/create`);
    await expect(page).toHaveURL(/\/create/);

    const playwrightRequest0: Record<string, any> = {
        "department": "Quality Assurance",
        "name": "New Test Employee",
        "position": "Software Engineer"
    };

    await page.locator("#name").fill(getValue(playwrightRequest0, "name"));
    await page.locator("#position").fill(getValue(playwrightRequest0, "position"));
    await page.locator("#department").fill(getValue(playwrightRequest0, "department"));
    await page.getByRole("radio", { name: "Junior" }).click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/record**");
    await page.getByRole("button", { name: "Save Employee Record" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page).toHaveURL(baseUrl + '/');
    await expect(page.getByRole("row", { name: "New Test Employee Software" }).last()).toContainText("Quality Assurance");
    expect(errors).toHaveLength(0);
});
