// Generated by Skyramp v1.3.38 on 2026-08-19 17:22:37.852473 -0700 PDT m=+565.452681209
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output department_field_edit_employee.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/.skyramp/department_field_edit_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5173");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(960000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/edit/6a86167fddf0da76c0f11273`);
    await expect(page).toHaveURL(/\/edit\//);
    // Wait for form data to load
    await page.waitForTimeout(3000);
    await page.waitForLoadState('networkidle');

    const playwrightRequest0: Record<string, any> = {"department": "Cloud Operations"};

    await page.locator("#department").fill(getValue(playwrightRequest0, "department"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/record/**");
    await page.getByRole("button", { name: "Save Employee Record" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(200);
    await expect(page).toHaveURL(baseUrl + '/');
    await expect(page.getByRole("row", { name: "Alice Chen Platform Engineer" })).toContainText("Cloud Operations");
    expect(errors).toHaveLength(0);
});
