// Generated by Skyramp v1.3.37 on 2026-08-11 13:32:52.622788 -0700 PDT m=+552.015031834
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output edit_employee_position_validation.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/.skyramp/edit_position_validation_trace.zip

// Import of required libraries
import { expect, newSkyrampPlaywrightPage, test } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/edit/abc123");
    await expect(page).toHaveURL(/\/edit\//);
    await expect(page.getByRole('heading', { name: 'Create/Update Employee Record' })).toBeVisible();
    await page.getByRole("button", { name: "Save Employee Record" }).click();
    await expect(page.getByText('Position is required.')).toBeVisible();
    expect(errors).toHaveLength(0);
});
