// Generated by Skyramp v1.3.37 on 2026-08-11 13:32:49.287017 -0700 PDT m=+548.679346043
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output position_error_clears_on_type.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/.skyramp/position_error_clears_trace.zip

// Import of required libraries
import { test, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(654000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173");
    await page.goto("http://localhost:5173/create");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.locator("#name").fill("Test Employee");
    await page.getByRole("button", { name: "Save Employee Record" }).click();
    await expect(page.getByText('Position is required.')).toBeVisible();
    await page.locator("#position").fill("S");
    await expect(page.getByText('Position is required.')).not.toBeVisible();
    await expect(page.locator("#position")).toHaveValue("S");
    expect(errors).toHaveLength(0);
});
