// Generated by Skyramp v1.3.37 on 2026-08-11 13:32:55.579492 -0700 PDT m=+554.971660501
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output position_error_not_on_initial_load.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/.skyramp/position_error_initial_load_trace.zip

// Import of required libraries
import { expect, newSkyrampPlaywrightPage, test } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:5173/create");
    await expect(page).toHaveURL(/\/create/);
    await expect(page.getByRole('heading', { name: 'Create/Update Employee Record' })).toBeVisible();
    await page.evaluate(() => { const allText = document.body.innerText; return allText.includes('Position is required.'); });
    await expect(page.getByText('Position is required.')).not.toBeVisible();
    await expect(page.locator("#position")).toHaveValue("");
    expect(errors).toHaveLength(0);
});
