// Generated by Skyramp v1.3.40 on 2026-08-29 15:31:16.796838256 +0000 UTC m=+951.208030783
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output record_create_persists_department_end_to_end.spec.ts \
// 		--output-dir /home/runner/work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mern-records-frontend/mern-records-frontend/mern-records-frontend/.skyramp/record_create_persists_department_end_to_end_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillEmployeeForm, selectEmployeeLevel, submitEmployeeForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5173");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1482000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/create`);

    const playwrightRequest0: Record<string, any> = {
        "department": "Field Engineering",
        "name": "Dept Probe",
        "position": "Solutions Engineer"
    };

    await fillEmployeeForm(page, getValue(playwrightRequest0, "name"), getValue(playwrightRequest0, "position"), getValue(playwrightRequest0, "department"));
    await selectEmployeeLevel(page, "Junior");
    await expect(page.getByRole("radio", { name: "Junior" })).toBeChecked();
    const response0 = await submitEmployeeForm(page);
    expect(response0.status()).toBe(200);
    await expect(page).toHaveURL(`${baseUrl}/`);
    await expect(page.getByRole("row").filter({ hasText: getValue(playwrightRequest0, "name") }).last().getByRole("cell", { name: getValue(playwrightRequest0, "department"), exact: true })).toHaveText(getValue(playwrightRequest0, "department"));
    await expect(page.getByRole("row").filter({ hasText: getValue(playwrightRequest0, "name") }).last().getByRole("cell", { name: getValue(playwrightRequest0, "position"), exact: true })).toHaveText(getValue(playwrightRequest0, "position"));
});
