// Generated by Skyramp v1.3.38 on 2026-08-19 17:25:25.363776 -0700 PDT m=+732.923061959
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output search_filters_employee_list.spec.ts \
// 		--output-dir /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/tests \
// 		--overwrite \
// 		--playwright-trace /Users/archit/actions-runner-mern-frontend-macos/_work/mern-records-frontend/mern-records-frontend/mern-records-frontend/.skyramp/search_filters_employee_list_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:5173");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(73000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.locator("#search").fill("Infrastructure");
    await expect(page.locator("#search")).toHaveValue("Infrastructure");
    await page.waitForSelector("text=Alice Chen");
    await expect(page.getByRole("row")).toHaveCount(2);
    await expect(page.getByRole("row", { name: "Alice Chen Platform Engineer" })).toContainText("Alice Chen");
    await expect(page.getByRole("row", { name: "Alice Chen Platform Engineer" })).toContainText("Infrastructure");
    expect(errors).toHaveLength(0);
});
