// Generated by Skyramp on 2026-08-29 15:32:28.123 Coordinated Universal Time


export async function fillEmployeeForm(page, name, position, department) {
    await page.locator("#name").fill(name);
    await page.locator("#position").fill(position);
    await page.locator("#department").fill(department);
}

export async function selectEmployeeLevel(page, level) {
    await page.getByRole("radio", { name: level }).click();
}

export async function submitEmployeeForm(page) {
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/record/**");
    await page.getByRole("button", { name: "Save Employee Record" }).click();
    const response0 = await responsePromise0;
    return response0;
}
